dist: bionic

language: python
python:
  - "3.8"

cache: pip

script:
  - python ./src/convertlists.py lists.json $HOME/ci/converted/ -d $HOME/ci/originals/ -vv
  - python ./src/buildrepo.py $HOME/ci/converted/ docs/ --base-url https://tamersaadeh.github.io/dnsbl-ci/ -vv

deploy:
  - provider: pages:git
    edge: true # needed until dpl v2 is released
    commit_message: Updated lists as of $(date +%Y-%m-%d)
    name: Deployment Bot
    email: deploy@travis-ci.org
    #target_branch: master
    verbose: true
    on:
      branch: master

branches:
  only:
    - master
