dist: bionic

language: python
python:
  - "3.8"

cache: pip

script:
  - python ./convertlists.py lists.json $HOME/ci/converted/ -vv
  - python ./buildrepo.py $HOME/ci/converted/ $HOME/ci/built/doc/ --downloadbaseurl https://tamersaadeh.github.io/dnsbl-ci/ -vv
  - rm -rf $HOME/ci/converted/

deploy:
  - provider: pages:git
    edge: true # needed until dpl v2 is released
    commit_message: Updated lists as of $(date +%Y-%m-%d)
    name: JustDomains CI
    email: justdomains-ci
    #local_dir: $HOME/ci/built/
    verbose: true
    on:
      branch: master

branches:
  only:
    - master
