dist: bionic

language: python
python:
  - "3.8"

env:
  global:
    - DEPLOY_BRANCH="master"
    - DEPLOY_BASE64_KEY_VAR="JUSTDOMAINS_LISTS_DEPLOY_KEY"
    - DEPLOY_REPO_SLUG="tamersaadeh/dnsbl-justdomains"
    - DEPLOY_TARGET_BRANCH="master"
    - DEPLOY_GIT_NAME="JustDomains CI"
    - DEPLOY_GIT_EMAIL="justdomains-ci"

script: 
  - python ./convertlists.py lists.json $HOME/ci/converted/ -vv
  - python ./buildrepo.py $HOME/ci/converted/ $HOME/ci/built/ # --downloadbaseurl https://justdomains.github.io/blocklists/ -vv

deploy:
  - provider: script
    script: .ci/deploy.sh $HOME/ci/built/
    on:
      branch: master

branches:
  only:
    - master
